# Generated by Django 5.2.8 on 2025-11-29 16:18

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kmstca', '0002_locationtag_topictag'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleIndex',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('subheading', 1), ('paragraph', 2), ('image', 6), ('quote', 12)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'icon': 'title'}), 1: ('wagtail.blocks.CharBlock', (), {'icon': 'h2'}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'ol', 'ul', 'hr', 'link']}), 3: ('wagtail.images.blocks.ImageBlock', [], {}), 4: ('wagtail.blocks.CharBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 3), ('caption', 4), ('source', 5), ('date', 5)]], {}), 7: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic']}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Who originally said or wrote this quote'}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'An optional qualifier for the quotee, such as their profession or role', 'required': False}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'An optional date for when this quote was said or written', 'required': False}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': 'An optional context for the quote, such as the work it comes from', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('text', 7), ('quotee', 8), ('quotee_qualifier', 9), ('date', 10), ('context', 11)]], {})})),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='LocationTaggedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_tagged_items', to='news.article')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_articles', to='kmstca.locationtag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='article',
            name='locations',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='news.LocationTaggedArticle', to='kmstca.LocationTag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='TopicTaggedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_tagged_items', to='news.article')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_articles', to='kmstca.topictag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='article',
            name='topics',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='news.TopicTaggedArticle', to='kmstca.TopicTag', verbose_name='Tags'),
        ),
    ]
