# Generated by Django 5.2.8 on 2025-11-29 20:03

import django.db.models.deletion
import modelcluster.contrib.taggit
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmstca', '0002_locationtag_topictag'),
        ('news', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='locations',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='news.LocationTaggedArticle', to='kmstca.LocationTag', verbose_name='Locations'),
        ),
        migrations.AlterField(
            model_name='article',
            name='topics',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='news.TopicTaggedArticle', to='kmstca.TopicTag', verbose_name='Topics'),
        ),
    ]
