# Generated by Django 5.2.8 on 2025-11-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_article_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('politics', 'Uettis'), ('world', 'Ardá'), ('science', 'Gnátiá'), ('culture', 'Teutá'), ('environment', 'Mbinektis'), ('business', 'Meiamtis'), ('crime', 'Uargdétiá'), ('sports', 'Gamán'), ('opinion', 'Gustus')], default='politics', max_length=64),
            preserve_default=False,
        ),
    ]
