# Generated by Django 5.2.8 on 2025-12-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmstca', '0003_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='colour_scheme',
            field=models.CharField(choices=[('primary', 'Primary'), ('accent', 'Accent'), ('green', 'Green'), ('cream', 'Cream')], default='accent', max_length=32),
        ),
    ]
