# Generated by Django 5.2.8 on 2025-12-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmstca', '0004_sitesettings_colour_scheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='KmstcaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copyright', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
