# Generated by Django 5.2.8 on 2025-11-30 13:15

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('colour', models.CharField(choices=[('primary', 'Primary'), ('accent', 'Accent'), ('green', 'Green'), ('cream', 'Cream')], max_length=16)),
                ('icon', models.CharField(max_length=32, verbose_name='BoxIcon class')),
                ('tagline', wagtail.fields.RichTextField()),
                ('pre_body', wagtail.fields.StreamField([('heading', 0), ('subheading', 1), ('paragraph', 2), ('image', 6), ('quote', 12)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'icon': 'title', 'template': 'blocks/heading.html'}), 1: ('wagtail.blocks.CharBlock', (), {'icon': 'h2', 'template': 'blocks/subheading.html'}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'ol', 'ul', 'hr', 'link']}), 3: ('wagtail.images.blocks.ImageBlock', [], {}), 4: ('wagtail.blocks.CharBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 3), ('caption', 4), ('source', 5), ('date', 5)]], {}), 7: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic']}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Who originally said or wrote this quote'}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'An optional qualifier for the quotee, such as their profession or role', 'required': False}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'An optional date for when this quote was said or written', 'required': False}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': 'An optional context for the quote, such as the work it comes from', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('text', 7), ('quotee', 8), ('quotee_qualifier', 9), ('date', 10), ('context', 11)]], {})}, verbose_name='Pre-index body')),
                ('post_body', wagtail.fields.StreamField([('heading', 0), ('subheading', 1), ('paragraph', 2), ('image', 6), ('quote', 12)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'icon': 'title', 'template': 'blocks/heading.html'}), 1: ('wagtail.blocks.CharBlock', (), {'icon': 'h2', 'template': 'blocks/subheading.html'}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'ol', 'ul', 'hr', 'link']}), 3: ('wagtail.images.blocks.ImageBlock', [], {}), 4: ('wagtail.blocks.CharBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 3), ('caption', 4), ('source', 5), ('date', 5)]], {}), 7: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic']}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Who originally said or wrote this quote'}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'An optional qualifier for the quotee, such as their profession or role', 'required': False}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'An optional date for when this quote was said or written', 'required': False}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': 'An optional context for the quote, such as the work it comes from', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('text', 7), ('quotee', 8), ('quotee_qualifier', 9), ('date', 10), ('context', 11)]], {})}, verbose_name='Post-index body')),
                ('cta_label', models.CharField(blank=True, max_length=128, verbose_name='Call to action label')),
                ('cta_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Call to action link')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='IndexPageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=64)),
                ('tagline', wagtail.fields.RichTextField(blank=True)),
                ('index_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='infodesk.indexpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('subheading', 1), ('paragraph', 2), ('image', 6), ('quote', 12)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'icon': 'title', 'template': 'blocks/heading.html'}), 1: ('wagtail.blocks.CharBlock', (), {'icon': 'h2', 'template': 'blocks/subheading.html'}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'ol', 'ul', 'hr', 'link']}), 3: ('wagtail.images.blocks.ImageBlock', [], {}), 4: ('wagtail.blocks.CharBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 3), ('caption', 4), ('source', 5), ('date', 5)]], {}), 7: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic']}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Who originally said or wrote this quote'}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'An optional qualifier for the quotee, such as their profession or role', 'required': False}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'An optional date for when this quote was said or written', 'required': False}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': 'An optional context for the quote, such as the work it comes from', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('text', 7), ('quotee', 8), ('quotee_qualifier', 9), ('date', 10), ('context', 11)]], {})})),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='infodesk.indexpagecategory')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
