# Generated by Django 5.2.8 on 2025-11-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infodesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexpage',
            name='colour',
            field=models.CharField(choices=[('primary', 'Primary'), ('accent', 'Accent'), ('green', 'Green'), ('cream', 'Cream')], default='primary', max_length=16),
        ),
    ]
