# Generated by Django 5.2.8 on 2025-11-30 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infodesk', '0003_alter_indexpage_post_body_alter_indexpage_pre_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexpage',
            name='cta_label',
        ),
        migrations.RemoveField(
            model_name='indexpage',
            name='cta_link',
        ),
    ]
