# Generated by Django 5.2.8 on 2025-12-02 21:59

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infodesk', '0004_remove_indexpage_cta_label_remove_indexpage_cta_link'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentpage',
            name='category',
        ),
        migrations.RenameModel(
            old_name='IndexPage',
            new_name='CategoryPage',
        ),
        migrations.CreateModel(
            name='IndexPageSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=64)),
                ('tagline', wagtail.fields.RichTextField(blank=True)),
                ('index_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='infodesk.categorypage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='contentpage',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='infodesk.indexpagesubcategory'),
        ),
        migrations.DeleteModel(
            name='IndexPageCategory',
        ),
    ]
