# Generated by Django 5.2.8 on 2025-12-02 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infodesk', '0005_remove_contentpage_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndexPageSubcategory',
            new_name='CategoryPageSubcategory',
        ),
        migrations.RenameField(
            model_name='categorypagesubcategory',
            old_name='index_page',
            new_name='category_page',
        ),
    ]
