# Generated by Django 5.2.8 on 2025-12-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infodesk', '0006_rename_indexpagesubcategory_categorypagesubcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='act_as_index',
            field=models.BooleanField(default=False, help_text='Display an alphabetized index of child pages'),
        ),
    ]
