# Generated by Django 5.2.8 on 2025-12-02 23:38

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infodesk', '0009_alter_categorypage_post_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorypage',
            name='post_body',
            field=wagtail.fields.StreamField([('heading', 0), ('subheading', 1), ('paragraph', 2), ('image', 6), ('quote', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'icon': 'title', 'template': 'blocks/heading.html'}), 1: ('wagtail.blocks.CharBlock', (), {'icon': 'h2', 'template': 'blocks/subheading.html'}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'ol', 'ul', 'hr', 'link']}), 3: ('wagtail.images.blocks.ImageBlock', [], {}), 4: ('wagtail.blocks.CharBlock', (), {'required': False}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('thumb', 'Thumbnail'), ('full', 'Full')]}), 6: ('wagtail.blocks.StructBlock', [[('image', 3), ('caption', 4), ('size', 5)]], {}), 7: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic']}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Who originally said or wrote this quote'}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'An optional qualifier for the quotee, such as their profession or role', 'required': False}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'An optional date for when this quote was said or written', 'required': False}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': 'An optional context for the quote, such as the work it comes from', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('text', 7), ('quotee', 8), ('quotee_qualifier', 9), ('date', 10), ('context', 11)]], {})}, verbose_name='Post-index body'),
        ),
        migrations.AlterField(
            model_name='categorypage',
            name='pre_body',
            field=wagtail.fields.StreamField([('heading', 0), ('subheading', 1), ('paragraph', 2), ('image', 6), ('quote', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'icon': 'title', 'template': 'blocks/heading.html'}), 1: ('wagtail.blocks.CharBlock', (), {'icon': 'h2', 'template': 'blocks/subheading.html'}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'ol', 'ul', 'hr', 'link']}), 3: ('wagtail.images.blocks.ImageBlock', [], {}), 4: ('wagtail.blocks.CharBlock', (), {'required': False}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('thumb', 'Thumbnail'), ('full', 'Full')]}), 6: ('wagtail.blocks.StructBlock', [[('image', 3), ('caption', 4), ('size', 5)]], {}), 7: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic']}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Who originally said or wrote this quote'}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'An optional qualifier for the quotee, such as their profession or role', 'required': False}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'An optional date for when this quote was said or written', 'required': False}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': 'An optional context for the quote, such as the work it comes from', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('text', 7), ('quotee', 8), ('quotee_qualifier', 9), ('date', 10), ('context', 11)]], {})}, verbose_name='Pre-index body'),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('subheading', 1), ('paragraph', 2), ('image', 6), ('quote', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'icon': 'title', 'template': 'blocks/heading.html'}), 1: ('wagtail.blocks.CharBlock', (), {'icon': 'h2', 'template': 'blocks/subheading.html'}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'ol', 'ul', 'hr', 'link']}), 3: ('wagtail.images.blocks.ImageBlock', [], {}), 4: ('wagtail.blocks.CharBlock', (), {'required': False}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('thumb', 'Thumbnail'), ('full', 'Full')]}), 6: ('wagtail.blocks.StructBlock', [[('image', 3), ('caption', 4), ('size', 5)]], {}), 7: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic']}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Who originally said or wrote this quote'}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'An optional qualifier for the quotee, such as their profession or role', 'required': False}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'An optional date for when this quote was said or written', 'required': False}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': 'An optional context for the quote, such as the work it comes from', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('text', 7), ('quotee', 8), ('quotee_qualifier', 9), ('date', 10), ('context', 11)]], {})}),
        ),
    ]
