# Generated by Django 5.2.14 on 2026-05-24 21:52

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infodesk', '0010_alter_categorypage_post_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorypage',
            name='post_body',
            field=wagtail.fields.StreamField([('heading', 0), ('subheading', 1), ('paragraph', 2), ('standout_text', 3), ('image', 7), ('quote', 13)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'icon': 'title', 'template': 'blocks/heading.html'}), 1: ('wagtail.blocks.CharBlock', (), {'icon': 'h2', 'template': 'blocks/subheading.html'}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'ol', 'ul', 'hr', 'link']}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'template': 'blocks/standout_text.html'}), 4: ('wagtail.images.blocks.ImageBlock', [], {}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('thumb', 'Thumbnail'), ('full', 'Full')]}), 7: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5), ('size', 6)]], {}), 8: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic']}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Who originally said or wrote this quote'}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'An optional qualifier for the quotee, such as their profession or role', 'required': False}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': 'An optional date for when this quote was said or written', 'required': False}), 12: ('wagtail.blocks.CharBlock', (), {'help_text': 'An optional context for the quote, such as the work it comes from', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('text', 8), ('quotee', 9), ('quotee_qualifier', 10), ('date', 11), ('context', 12)]], {})}, verbose_name='Post-index body'),
        ),
        migrations.AlterField(
            model_name='categorypage',
            name='pre_body',
            field=wagtail.fields.StreamField([('heading', 0), ('subheading', 1), ('paragraph', 2), ('standout_text', 3), ('image', 7), ('quote', 13)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'icon': 'title', 'template': 'blocks/heading.html'}), 1: ('wagtail.blocks.CharBlock', (), {'icon': 'h2', 'template': 'blocks/subheading.html'}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'ol', 'ul', 'hr', 'link']}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'template': 'blocks/standout_text.html'}), 4: ('wagtail.images.blocks.ImageBlock', [], {}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('thumb', 'Thumbnail'), ('full', 'Full')]}), 7: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5), ('size', 6)]], {}), 8: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic']}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Who originally said or wrote this quote'}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'An optional qualifier for the quotee, such as their profession or role', 'required': False}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': 'An optional date for when this quote was said or written', 'required': False}), 12: ('wagtail.blocks.CharBlock', (), {'help_text': 'An optional context for the quote, such as the work it comes from', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('text', 8), ('quotee', 9), ('quotee_qualifier', 10), ('date', 11), ('context', 12)]], {})}, verbose_name='Pre-index body'),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('subheading', 1), ('paragraph', 2), ('standout_text', 3), ('image', 7), ('quote', 13)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'icon': 'title', 'template': 'blocks/heading.html'}), 1: ('wagtail.blocks.CharBlock', (), {'icon': 'h2', 'template': 'blocks/subheading.html'}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'ol', 'ul', 'hr', 'link']}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'template': 'blocks/standout_text.html'}), 4: ('wagtail.images.blocks.ImageBlock', [], {}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('thumb', 'Thumbnail'), ('full', 'Full')]}), 7: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5), ('size', 6)]], {}), 8: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic']}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Who originally said or wrote this quote'}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'An optional qualifier for the quotee, such as their profession or role', 'required': False}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': 'An optional date for when this quote was said or written', 'required': False}), 12: ('wagtail.blocks.CharBlock', (), {'help_text': 'An optional context for the quote, such as the work it comes from', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('text', 8), ('quotee', 9), ('quotee_qualifier', 10), ('date', 11), ('context', 12)]], {})}),
        ),
    ]
