# Generated by Django 5.2.8 on 2025-12-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='heading',
            field=models.CharField(default='Ceme uelé', max_length=511),
            preserve_default=False,
        ),
    ]
